#!/usr/bin/env python
# EXTRACCION DE METADATA DE UN PDF
# @RojasKnight
#/
#/
#/
#_______________________________.
import optparse                #|
import pyPdf                   #|
from pyPdf import PdfFileReader#|
#_______________________________|

def ImprimeMetadatos(archivoPDF):
    pdfFile =PdfFileReader(file(archivoPDF,"rb"))
    datos=pdfFile.getDocumentInfo()
    print "[*] Metadatos obtenidos de: " +str(archivoPDF), ""

    for metaItem in datos:
        print "[+] "+ metaItem +':' + datos[metaItem]
    print "Programa Finalizado :)"


def main():

    parser = optparse.OptionParser("./prog -F <Nombre del PDF>")
    parser.add_option("-F", dest="NombrePDF", type="string", help="Especifique el nombre del PDF")
    (options, args) = parser.parse_args()

    archivo = options.NombrePDF

    if archivo == None:
        print "[*]El PDF No existe"
        parser.print_help()
        exit(0)
    else:
        ImprimeMetadatos(archivo)

if __name__=="__main__":
    main()
